spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: 123456
mybatis:
  mapper-locations: bootTest/mapper/*.xml
  type-aliases-package: bootTest.pojo

#pagehelper:                       #pagehelper分页插件
#  helperDialect: mysql          #设置数据库方言
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql