spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=gb2312&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: myboot.pojo

server:
  port: 8080