spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT
    password: root
    username: root
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: templates
  security:
    user:
      name: user
      password: user
      roles: admin

mybatis:
  mapper-locations: classpath:xmlmap/*Mapper.xml
  type-aliases-package: boot.mystaic.myweb.pojo
  type-handlers-package: boot.mystaic.myweb.secret

system:
  user:
    password:
      secret: inview