spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT
    password: 123456
    username: root
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:xmlmap/*Mapper.xml
  type-aliases-package: boot.mystaic.myweb.pojo