spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3306/wuhan_illegal_construction?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: sql/schema-buildTable.sql
    data: sql/data-*.sql

  jpa:
    show-sql: true
mybatis-plus:
  global-config:
    db-config:
      table-underline: true
  type-enums-package: com.wuhan.illegalconstruction.enums